[pytest]
pythonpath = .
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20

markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
    unit: marks tests as unit tests (deselect with '-m "not unit"')

# Default to running only unit tests
addopts = -m "unit"
